import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body style={{
        margin: 0,
        padding: 0,
        backgroundImage: 'url("/resturantbgphoto.png")', // Make sure bg.jpg is inside /public folder
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        height: '100vh',
        width: '100vw',
        position: 'relative',
      }}>
        <div>hello</div>
        {children}
      </body>
    </html>
  );
}


